module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier', 'prettier/react'],
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  env: {
    browser: true,
    commonjs: true,
    jest: true,
  },
  rules: {
    'no-await-in-loop': 'off',
    'valid-jsdoc': 'error',
    'class-methods-use-this': 'error',
    'consistent-return': 'off',
    'default-case': ['error', { commentPattern: '^no default$' }],
    'no-magic-numbers': [
      'error',
      {
        ignore: [],
        ignoreArrayIndexes: true,
        enforceConst: true,
        detectObjects: false,
      },
    ],
    'no-catch-shadow': 'error',
    'no-mixed-requires': 'error',
    'no-mixed-operators': [
      'error',
      {
        groups: [
          ['%', '**'],
          ['%', '+'],
          ['%', '-'],
          ['%', '*'],
          ['%', '/'],
          ['**', '+'],
          ['**', '-'],
          ['**', '*'],
          ['**', '/'],
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: false,
      },
    ],
    'require-jsdoc': 'error',
    'no-console': 'warn',
    'require-await': 'error',
    'vars-on-top': 'error',
    'init-declarations': 'off',
    'global-require': ['off', false],
    'no-process-env': 'off',
    'no-process-exit': 'off',
    'no-sync': 'off',
    'no-bitwise': 'off',
    'no-prototype-builtins': 'error',
    'no-alert': 'error',
    'no-eq-null': 'error',
    'no-warning-comments': [
      'off',
      { terms: ['todo', 'fixme', 'xxx'], location: 'start' },
    ],
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-ternary': 'off',
    'no-underscore-dangle': [
      'error',
      {
        allow: [],
        allowAfterThis: false,
        allowAfterSuper: false,
        enforceInMethodNames: false,
      },
    ],
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'no-cond-assign': ['error', 'except-parens'],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-irregular-whitespace': [
      'error',
      {
        skipStrings: true,
        skipComments: false,
        skipRegExps: true,
        skipTemplates: true,
      },
    ],
  },
};
